### PR TITLE
Fix two issues

### PR DESCRIPTION
**Pull request by lychichem**
1. Use correct IP for collector.githubapp.com. The IP `34.237.209.114` is configured for `tableau.cellsignal.com` but not `collector.githubapp.com`.
2. Add a server which hosts Widevine DRM plugin provided by Google for Firefox. Works at leaset on Firefox 64 bit version on Windows. I don't know whether this plugin for other platform is hosted on the same server, so other servers maybe need to add to the list.

### CODE REVIEW

**Comment by lennylxx** [comment]
@lychichem You mean the plugin is hosted on `r2.sn-vgqseney.gvt1.com`? Interesting.

**Comment by lychichem** [comment]
@lennylxx Firefox call this plugin as Widevine DRM module provided by Google, so this is reasonable that Google puts this plugin on their server. And actually, a new install of Firefox will contain two "gmp-plugin", one is openh264 by cisco and the other is above. Both need to be downloaded from the Internet. But widevine always fail to download. The link is catched by using xx-net and view the log and cert generated. You can see https://wiki.mozilla.org/GeckoMediaPlugins for more about gmp-plugin.

**Comment by lennylxx** [comment]
According to https://support.mozilla.org/en-US/questions/1162618, it uses a redirect domain, some thing like `https://redirector.gvt1.com/edgedl/widevine-cdm/903-win-x64.zip`. So adding only one `gvt1.com` won't be enough and I don't think it works for others.

**Comment by lennylxx** [comment]
Source code: https://github.com/mozilla/gecko-dev/blob/master/toolkit/content/gmp-sources/widevinecdm.json

**Comment by lychichem** [comment]
@lennylxx Okay let's forget widevine. Please just merge the first part of this pull request.

**Comment by lennylxx** [comment]
@lychichem Okay, could you please update your PR?

**Comment by lychichem** [comment]
Finished.

**Pull request merged**
