### PR TITLE
Google Code/Source: add fetch chromium support

### PR DESCRIPTION
**Pull request by lrinQVQ**

### CODE REVIEW

**Comment by lennylxx** [comment]
It's still not quite right, please run command `rm hosts && ./merge_snippets.sh` and add your new changes to this pull request.

**Comment by lrinQVQ** [comment]
Sorry XD I forget ./merge_snippets.sh

**Comment by lennylxx** [comment]
Good job! Thank you.

**Comment by lrinQVQ** [comment]
@lennylxx ok~ you are welcome

**Pull request merged**
