### PR TITLE
update googlevideo

### PR DESCRIPTION
**Pull request by RomanSmile**
add
ntnxax8xo-cxge
gvnuxaxjvh-aome
bvvbax-qxose
bvvbax-hn26
bvvbax-hn2d
bvvbax-hn2k
4gxx-hgns
4gxx-hgnz
oapm-guhe
oapm-guhl
oapm-guhs
oapm-guhz
bvvbax-n8me
bvvbax-n8ml
bvvbax-2ime
bvvbax-2iml
bvvbax-2ims
buu-hp5s
bvvbax-hjpe
bvvbax-hjpl
bvvbax-4jve
bvvbax-nuae
bvvbax-nual
bvvbax-itqe
bvvbax-b05e
bvvbax-a5ne
bvvbax-a5nl
bvvbax-2iae

### CODE REVIEW

**Comment by lennylxx** [comment]
This PR titled with "update googlevideo" but the change file list contains `1e100.txt`, Could you please separate it?

**Comment by RomanSmile** [comment]
好吧我把这个请求关闭，从新发一个好吗？

**Comment by RomanSmile** [comment]
@lennylxx 
我向ppoozl提出的话题不知道接受了没有，明确的说他更新添加的ggc有些是坏死的，

**Comment by lennylxx** [comment]
我刚才检查了一下，他添加的DNS都能查到，但是因为我现在没有IPv6环境，不能测试`ping` 和`curl`。
你说的坏死是指你连不上？不同的网络环境有可能不同，如果教育网IPv6也连不上，那么就可以删掉这些。

**Comment by RomanSmile** [comment]
2404:b0:c:88::c r1---sn-jnavmpo4v-c33s.googlevideo.com
2404:b0:c:88::d r2---sn-jnavmpo4v-c33s.googlevideo.com
2404:b0:c:88::e r3---sn-jnavmpo4v-c33s.googlevideo.com
2404:b0:c:88::f r4---sn-jnavmpo4v-c33s.googlevideo.com
2404:b0:c:89::c r1---sn-jnavmpo4v-c33l.googlevideo.com
2404:b0:c:89::d r2---sn-jnavmpo4v-c33l.googlevideo.com
2404:b0:c:89::e r3---sn-jnavmpo4v-c33l.googlevideo.com
2404:b0:c:89::f r4---sn-jnavmpo4v-c33l.googlevideo.com
#####
2402:800:6150:10::c r1---sn-8pxuuxa-i5or.googlevideo.com
2402:800:6150:10::d r2---sn-8pxuuxa-i5or.googlevideo.com
2402:800:6150:10::e r3---sn-8pxuuxa-i5or.googlevideo.com
2402:800:6150:10::f r4---sn-8pxuuxa-i5or.googlevideo.com
2402:800:6150:10::10 r5---sn-8pxuuxa-i5or.googlevideo.com
2402:800:6150:10::11 r6---sn-8pxuuxa-i5or.googlevideo.com
2402:800:6150:10::12 r7---sn-8pxuuxa-i5or.googlevideo.com
2402:800:6150:10::13 r8---sn-8pxuuxa-i5or.googlevideo.com
####
2404:b0:c:88::c r1---sn-jnavmpo4v-c33s.googlevideo.com
2404:b0:c:88::d r2---sn-jnavmpo4v-c33s.googlevideo.com
2404:b0:c:88::e r3---sn-jnavmpo4v-c33s.googlevideo.com
2404:b0:c:88::f r4---sn-jnavmpo4v-c33s.googlevideo.com
2404:b0:c:89::c r1---sn-jnavmpo4v-c33l.googlevideo.com
2404:b0:c:89::d r2---sn-jnavmpo4v-c33l.googlevideo.com
2404:b0:c:89::e r3---sn-jnavmpo4v-c33l.googlevideo.com
2404:b0:c:89::f r4---sn-jnavmpo4v-c33l.googlevideo.com
####
2404:8000:10:22::c r1---sn-cp1oxu-jb3e.googlevideo.com
2404:8000:10:22::d r2---sn-cp1oxu-jb3e.googlevideo.com
2404:8000:10:22::e r3---sn-cp1oxu-jb3e.googlevideo.com
2404:8000:10:22::f r4---sn-cp1oxu-jb3e.googlevideo.com

**Comment by roc1010kmt** [comment]
he隧道突然特別慢，是他服務器抽風還是牆封鎖？

**Comment by lennylxx** [comment]
@RomanSmile 你是教育网直连吗？

**Comment by ppoozl** [comment]
GGC本来就是别人网络做CDN的，你连不上不代表别人连不上啊，我的原则是DNS有记录能查到就添加了

**Comment by ppoozl** [comment]
image

**Comment by ppoozl** [comment]
lax HE隧道

**Comment by ppoozl** [comment]
image
image
image

**Comment by ppoozl** [comment]
@RomanSmile

**Pull request merged**
