### PR TITLE
Format improvement

### PR DESCRIPTION
**Pull request by Phecda**
1. Sort the addresses in `SN编码` part of `08_googlevideo.txt`.
2. Delete all commented addresses in that part.

### CODE REVIEW

**Comment by hoschi111** [comment]
it's possible, that commented addresses are just temporary not available. Maybe deleting them is not the best idea.

**Comment by Phecda** [comment]
THX for your comment. I had hesitated for a long time before making this decision, then I realized that, when we need to use these commented hosts again, we will run `update_hosts.py` to check whether their old IP are available or they have new IP, which has the same procedures as finding addresses for new hostname. Now that what we need to do are the same, would it be better to delete them to reduce file size?

**Comment by hoschi111** [comment]
In my opinion, we should leave it how it is. A long term test could show us, how many domains will be available over IPv6 again. Furthermore doen't it save that much space after cleaning, it's still more than 1 MB in filesize.

**Comment by lennylxx** [comment]
Thanks for the contribution, but I agree with @hoschi111 , I kept the commented lines incase it's available someday, and it did happen before. Also, not all the domains are ordered by alphabet, some of them are sorted by IP addresses, others are sorted by domain names, some are sorted by product/service. Maybe another PR just for updating and keep the commit number as little as possible?  So we will have a clean git history instead of lots of merging message of each other.

**Comment by Phecda** [comment]
OK, I'll open another PR. And about sorting, I only sorted `SN编码` in IP address ascending order to make it easy to inserting new address, because I read this in [wiki-step 6](https://github.com/lennylxx/ipv6-hosts/wiki/Do-It-Yourself#%E4%BA%8C%E5%A2%9E%E5%8A%A0-googlevideo-%E6%9C%8D%E5%8A%A1%E5%99%A8-sn-domains). May I do this again in new PR, or just update new addresses? @lennylxx

**Comment by lennylxx** [comment]
Sure, absolutely, as long as you keep most of them in order. 
I haven't seen the details of the host file for a long time so I don't remember the sorting way it uses for this `googvideo` file, I think it has several orders, be careful when you deal with it and the less changes are better. 
Also please pay attention to these highlighted domains at the bottom of this page https://github.com/lennylxx/ipv6-hosts/wiki/How-to-speed-up, they must be set manually

**Pull request closed without merging**
